# Generated by Django 3.2.2 on 2021-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xx', '0027_alter_clicommand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpi',
            name='id_rsa_pub',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
